// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/YungBenn/tech-shop-microservices/internal/product/handler"
	"github.com/YungBenn/tech-shop-microservices/internal/product/message"
	"github.com/YungBenn/tech-shop-microservices/internal/product/pb"
	"github.com/YungBenn/tech-shop-microservices/internal/product/repository"
	"github.com/confluentinc/confluent-kafka-go/v2/kafka"
	"github.com/sirupsen/logrus"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitProductService(db *mongo.Database, log *logrus.Logger, Producer *kafka.Producer, Topic string) pb.ProductServiceServer {
	productRepository := repository.NewProductRepository(db, log)
	kafkaProducerRepository := message.NewKafkaProducerRepository(Producer, Topic)
	productServiceServer := handler.NewProductServiceServer(log, productRepository, kafkaProducerRepository)
	return productServiceServer
}
