// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/YungBenn/tech-shop-microservices/internal/cart/handler"
	pb2 "github.com/YungBenn/tech-shop-microservices/internal/cart/pb"
	"github.com/YungBenn/tech-shop-microservices/internal/cart/repository"
	"github.com/YungBenn/tech-shop-microservices/internal/product/pb"
	"github.com/redis/go-redis/v9"
	"github.com/sirupsen/logrus"
)

// Injectors from wire.go:

func InitCartService(client pb.ProductServiceClient, log *logrus.Logger, rdb *redis.Client) pb2.CartServiceServer {
	cartRepository := repository.NewCartRepository(rdb)
	cartServiceServer := handler.NewCartServiceServer(client, log, cartRepository)
	return cartServiceServer
}
